# Generated by Django 5.2 on 2025-05-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('title', 'company_name', 'location')},
        ),
    ]
